### ISSUE TITLE
Implement Attributes Values Formatting

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#199]
### Subtasks
- [ ] Implement formatting handler with set of methods ( class-formatting ), which will take care about all attributes formatting in plugin. See example: https://github.com/wp-property/wp-property/blob/v2.0-legacy/lib/class-formatting.php
- [ ] Rename 'Currency & Numbers' section on Settings page ( Display Tab ) to 'Attributes Formatting' and add titles for every UI settings like 'Currency', 'Numbers', 'Checkboxes (Yes, No)', etc. See: http://screencast.com/t/h8ePHLpW8FF
- [ ] Get rid of Checkbox UI ( Single Checkbox type ) in different places. Create the only one option, which will be used in all cases in 'Attributes Formatting' section.  See: http://screencast.com/t/qjqW1q0tKrf ,  http://screencast.com/t/oaOVS9Uabko
- [ ] Implement human formatting for Single Checkbox. Get rid of custom formatting in different places.
- [ ] Implement human formatting for Currency. Get rid of custom formatting in different places.
- [ ] Implement human formatting for Numeric. Get rid of custom formatting in different places. Split currency and numbers UI and formatting.
- [ ] Implement human formatting for URL.
- [ ] Implement human formatting for Oembed.
- [ ] Implement human formatting for Image Upload.
- [ ] Implement human formatting for Date And Time picker.
- [ ] Implement human formatting for Date picker. 
- [ ] Implement human formatting for Time picker. 
- [ ] Implement human formatting for Color picker. 
- [ ] Implement human formatting for Files Upload. 
- [ ] Implement human formatting for File URL. 
- [ ] Implement human formatting for File URL. 
  *[ ] Move value formatting from draw_stats() function to class-formatting.php
### Objectives

Need to implement the following formatting of attributes values via WP filters:
- system
- edit
- human

The following code can be used as example: 
https://github.com/wp-property/wp-property/blob/v2.0-legacy/lib/class-formatting.php

Requirements:  
- use 'develop-formatting' branch.
- create lib/classes/class-formatting.php.
- file must be autoloaded via composer.
- value formatting must belong to attribute type.
- every attribute type must have 3 methods for formatting value ( system, edit, human ). The methods must be called via hooks.

Notes:
- Attribute Type ( Data Entry ) is set on Developer tab ( http://screencast.com/t/eSCit38mP ). 
- Attributes types are defined in lib/classes/class-attributes.php. See: ud_get_wp_property()->set( 'attributes.types', array(...) );
#### system

System value which is used for storing in DB and can be used for search engine, etc.
Attribute's value must be converted on property saving/updating.
#### edit

Editable value for Edit Property Page.
Attribute's value must be converted for using it on Edit Property Page.
#### human

The value to show it on front end. 
##### checkbox

Formatting functionality already exists in plugin. But it's not good implemented. There are a lot of places where checkbox values are being converted to 'Yes/No' or image values.

Need to get rid of that functionality and move logic to 'formatting' class.

Bad Examples of current usage: 
- http://screencast.com/t/sCgZlDx2
- http://screencast.com/t/MosYrF21jSAA
##### currency

Formatting functionality already exists in plugin. But it's not good implemented. There are a lot of places where checkbox values are being converted to 'Yes/No' or image values.

Need to get rid of that functionality and move logic to 'formatting' class.

Current Currency Options: http://screencast.com/t/h0pBJ01a
##### numeric

Split currency and numeric attributes formatting and UI.
##### multi checkbox

Values via comma by default.
Should be added UI: show values via comma or list.

list means `<ul><li>`
##### url

URL should be wrapped to <a> link
##### oembed

Use native Wordpress features to show video on front end.
For example, if you provide the link to youtube video in Editor ( the_content ) on Edit Property Page, it will be automatically converted to video on Front End by default ( it's native WP behaviour ).
##### date and time picker

Use WordPress Date and Time Format for formatting. See: http://screencast.com/t/g4jur39QFLg
##### date picker

Use WordPress Date Format for formatting.
##### time picker

Use Wordpress Time Format for formatting.
##### color picker

Show 75x25 div element with defined background color.
##### image upload

use shortcode for rendering images on Front End.
Example: `[gallery ids="1855,1676"]`

We also should add some UI settings on 'Attributes Formatting' section.
UI Settings: http://screencast.com/t/jQtVqqHTk0jI
##### files upload

The list of `<a>` links using `<ul><li>`
##### file url

URL should be wrapped to `<a>` link

**Comment by pemaxim** [comment]
Move value formatting from draw_stats() function to class-formatting.php
See: 
https://github.com/wp-property/wp-property/commit/dfe64bf197d133b0f7d42e0bd07baf23430b7864#commitcomment-14822000
